export const mockDataList = [
  {
    adult: false,
    backdrop_path: "/pdfCr8W0wBCpdjbZXSxnKhZtosP.jpg",
    id: 84773,
    name: "The Lord of the Rings: The Rings of Power",
    original_language: "en",
    original_name: "The Lord of the Rings: The Rings of Power",
    overview:
      "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
    poster_path: "/suyNxglk17Cpk8rCM2kZgqKdftk.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 18],
    popularity: 1142.628,
    first_air_date: "2022-09-01",
    vote_average: 6.977,
    vote_count: 111,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/1DBDwevWS8OhiT3wqqlW7KGPd6m.jpg",
    id: 985939,
    title: "Fall",
    original_language: "en",
    original_title: "Fall",
    overview:
      "For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights.",
    poster_path: "/v28T5F1IygM8vXWZIycfNEm3xcL.jpg",
    media_type: "movie",
    genre_ids: [53],
    popularity: 456.117,
    release_date: "2022-08-11",
    video: false,
    vote_average: 7.214,
    vote_count: 49,
  },
];

export const mockDataSectionList = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg",
      genre_ids: [16, 878, 28],
      id: 610150,
      original_language: "ja",
      original_title: "ドラゴンボール超 スーパーヒーロー",
      overview:
        'Son Goku destruyó en su momento al Ejército Red Ribbon. Ahora, ciertos individuos han decidido continuar con su legado y han creado a los androides definitivos: Gamma 1 y Gamma 2. Estos dos androides se autoproclaman "superhéroes" y deciden atacar a Piccolo y a Gohan. ¿Cuál es el objetivo del Nuevo Ejército Red Ribbon?  Ante un peligro inminente, ¡llega el momento del despertar del Superhéroe!',
      popularity: 14296.269,
      poster_path: "/gPwXtxnEgppVaMsrpPNajw1K7LH.jpg",
      release_date: "2022-06-11",
      title: "Dragon Ball Super: Super Hero",
      video: false,
      vote_average: 7.9,
      vote_count: 825,
    },
    {
      adult: false,
      backdrop_path: "/vvObT0eIWGlArLQx3K5wZ0uT812.jpg",
      genre_ids: [28, 12, 14],
      id: 616037,
      original_language: "en",
      original_title: "Thor: Love and Thunder",
      overview:
        'Cuarta película sobre "Thor" del MCU, en la que el Dios del trueno contará con Lady Thor como acompañante, personaje que interpretará Natalie Portman.',
      popularity: 4846.318,
      poster_path: "/4VkGlhGHUzZjnkoYNasW0qhoP3R.jpg",
      release_date: "2022-07-06",
      title: "Thor: Love and Thunder",
      video: false,
      vote_average: 6.8,
      vote_count: 2200,
    },
  ],
  total_pages: 34964,
  total_results: 699270,
};

export const mockDataMovieCredits = [
  {
    adult: false,
    gender: 2,
    id: 488,
    known_for_department: "Directing",
    name: "Steven Spielberg",
    original_name: "Steven Spielberg",
    popularity: 24.431,
    profile_path: "/tZxcg19YQ3e8fJ0pOs7hjlnmmr6.jpg",
    credit_id: "5ef319762b210800359055ef",
    department: "Production",
    job: "Executive Producer",
  },
];
